### ISSUE TITLE
documentation: I need more "meat" about - for what this module need?

### ISSUE THREAD

**Issue by cybermerlin** [typeorm/typeorm-typedi-extensions#20]
Why haven't I use clear typeorm connections?

```
import {data.Model as DataModel} from 'Core';
class Account extends DataModel {
    @Column({readonly: false, select: true, type: 'text', nullable: false, primary: false, unique: true, array: false})
    name;
}
let user = new Account();
user.find({name: 'pupi', limit: 1})

console.info(user.name)
```

That's my simple example. Maybe typedi give me more usabilities?

**Comment by 19majkel94** [comment]
Try to mock access to database in your controllers when you rely on global static class (DataModel) :wink:

That's why TypeORM supports also data mapper pattern with repositories which mediate between controllers and database, providing abstraction layer. You can then use TypeDI for dependency injection which is really helpful in testing.

```ts
@Service()
@JsonController("/dictionaries")
export class DictionaryController {
    constructor(
        @OrmRepository() private dictionaryRepository: DictionaryRepository,
    ) {}

    @Get()
    async getAll(): Promise<Dictionary[]> {
        return this.dictionaryRepository.findAll();
    }
}
```
