### ISSUE TITLE
How to inject repository when using separate entity schema and not decorators?

### ISSUE THREAD

**Issue by madshargreave** [typeorm/typeorm-typedi-extensions#26]
If I have an separate entity schema like such

```
export const ProjectEntity = new EntitySchema<Project>({
    name: 'project',
    columns: {
        id: {
            type: Number,
            primary: true,
            generated: true
        },
        userId: {
            type: Number,
        },
        name: {
            type: String,
            nullable: false
        }
    }
})

```

And a corresponding service

```
@Service(Services.PROJECT)
export class ProjectService {

    constructor (
        @InjectRepository(Project) private repository: ProjectRepository
    ) {}
```

The the following error will be thrown when trying to instantiate the service

```
No metadata for \"Project\" was found.
```

**Comment by pleerock** [comment]
I think you shall use entity schema name, e.g. `@InjectRepository("project")`

**Comment by netoec84** [comment]
> I think you shall use entity schema name, e.g. `@InjectRepository("project")`

It does not work, because you get an error: 
`Argument of type '"project"' is not assignable to parameter of type 'Function`

I think you should use something like:
`@InjectRepository(ProjectEntity) private repository: ProjectRepository`

typeorm defined like:
[code here](https://github.com/typeorm/typeorm/blob/a858de1f195d41aaffdeb8c10faa538dc1a15f5c/src/connection/Connection.ts#L341)
```
  getRepository<Entity>(target: ObjectType<Entity>|EntitySchema<Entity>|string): Repository<Entity> {
        return this.manager.getRepository(target);
    }
```

But, you should also make changes to the method definitions in:
TypeOrmModule.forFeature to support EntitySchema, maybe something like:
```
static forFeature(entities?: Function[] | EntitySchema<any>[], connection?: Connection | ConnectionOptions | string): DynamicModule;
```

and typeorm.decorators.ts like:
```
export declare const InjectRepository: (entity: Function | EntitySchema<any>, connection?: string) => (target: Object, key: string | symbol, index?: number) => void;
```

I changed the code in the .d.ts files and it worked. But I think that changing the source code can present other problems. Do you think that could be a solution?
